export const DEFAULT_ESTIMATED_HEIGHT = 100;
export const SCROLL_THROTTLE_MS = 100;
export const MEASURE_UPDATE_DEBOUNCE_MS = 50;
export const SCROLL_DEBOUNCE_MS = 700;
export const DEFAULT_OFFSCREEN_ITEMS_HEIGHT_RATIO = 1;
